# in order to import plot, print and str for kanjivec we need (only) the generics
# plot and print are in base, so we only need to import str from utils
#' @importFrom utils str
#' @importFrom kanjistat get_strokes get_strokes_compo
NULL

#' Data in `kanjivec` format
#'
#' @description `kvecjoyo` is a list of all 2136 current jouyou kanji (as last specified by the Japanese Ministry
#' of Education in 2010).
#' 
#' @description `kvecjoyo` is a list of those 774 out of all 863 current jinmeiyou
#' (as last adapted by the Japanese Ministry of Justice in 2017).
#'
#' @format Each list element is an object of the S3 class `kanjivec`, see [kanjistat::kanjivec()].
#'   
#' @source The lists have been generated by [kanjistat::kanjivec()] 
#' with parameter \code{flatten="intelligent"} under kanjistat version 0.13.0 (`kvecjoyo`)
#' and 0.13.1 (`kvecjinmeiyou`) based on the KanjiVG database by Ulrich Apel
#' <https://kanjivg.tagaini.net/>.
#'  
#' @examples 
#' plot(kvecjoyo[[869]])
#' plot(kvecjoyo[[869]], type="dend")
#' kvecjoyo[[869]]
#' str(kvecjoyo[[869]])
#' kanjistat::get_strokes(kvecjoyo[[869]], 10)  # the tenth stroke of the kanji 
#'
#' @name kvec
NULL

#' @format NULL
#' @rdname kvec
"kvecjoyo"

#' @format NULL
#' @rdname kvec
"kvecjinmei"


#' The component-transport distance matrix
#'
#' A matrix of pairwise distances between jouyou kanji based on visual similarity
#' computed with the [kanjistat::kanjidist()] function. 
#'
#' @format A 2136 x 2136 symmetric numeric matrix of distance values
#' between 0 and 0.25 with row and column names specifying
#' the corresponding jouyou kanji in the usual order used in the kanjistat
#' package, e.g. for [kanjistat::kbase].
#' 
#' @source The matrix has been generated by computing the individual entries
#' in kanjistat v0.13.1 as
#' ```
#'    kanjidist(k1, k2, compo_seg_depth1 = 4, compo_seg_depth2 = 4,               
#'              p = 1, C = 0.2, approx = "pcweighted", type = "rtt") 
#' ```
#' where k1 and k2 are kanjivec objects of the two kanji considered. 
#'  
#' @section Warnings:
#'
#' While the distance matrix seems to be useful for obtaining sets of similar
#' looking kanji (see the Examples below), there is a number of caveats:
#' 
#' * Neither the distances nor the neighborhoods of similar looking kanji
#'   are very useful for several of the kanji composed of very few
#'   strokes. This is mainly because the [kanjistat::kanjidist()] code
#'   does currently not consider individual strokes as components.
#'   
#' * In some cases the neighborhoods are inadequate due to
#'   a suboptimal decomposition of the kanji (suboptimal
#'   for the task at hand, that is). This is sometimes already based in the 
#'   structure of the kanjiVG file, but more often due to a lack of refinement
#'   in the processing of special cases by [kanjistat::kanjivec()].
#'  
#' * The distances do not satisfy the triangle inequality, i.e. we find many
#'   combinations of i,j and k such that `dct[i,j] <= dct[i,k] + dct[k,j]` does
#'   not hold. This is by design as the underlying component-transport distance
#'   is not a metric.
#'   
#' While the first two points are clearly undesirable and will be improved on 
#' in the future, the last point helps in the construction of the component-transport
#' distance function and is backed by research in cognitive psychology indicating
#' that human similarity judgment are better described by non-metric structures
#' (e.g. a strong feeling of similarity is triggered when a certain threshold in
#' "objective" similarity is passed). See Remark 1 of the reference below.
#' 
#' @references Dominic Schuhmacher (2023).\cr
#'             Distance maps between Japanese kanji characters based on hierarchical optimal transport.\cr
#'             ArXiv, \doi{10.48550/arXiv.2304.02493}
#'  
#' @examples 
#' dct[700:708, 700:708]
#' sort(dct[356,])[1:20]
"dct"


#' The embeddings distance matrix
#'
#' A matrix of pairwise distances between jouyou kanji based on similar semantics
#' computed using OpenAI's text embeddings.
#'
#' @format A 2136 x 2136 symmetric numeric matrix of distance values
#' between 0 and 0.25 with row and column names specifying
#' the corresponding jouyou kanji in the usual order used in the kanjistat
#' package, e.g. for [kanjistat::kbase].
#' 
#' @source Generated by Lennart Finke using [OpenAI's text embeddings](https://platform.openai.com/docs/guides/embeddings).
#' Python code https://github.com/dschuhmacher/kanjistat.data/tree/main/data-raw
#'  
#' @details TO DO.
#'  
#' @examples 
#' dembed[100:108, 100:108]
#' sort(dembed[158,])[1:20]
"dembed"
